jdstore/config/routes.rb
Rails.application.routes.draw do
  # root 'products#index'
  devise_for :users

  namespace :admin do
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :products
  end

  resources :products do
    collection do
      get :search
    end

    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  get '/welcome' => 'welcome#index'
  root 'welcome#index'
end

jdstore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jdstore/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product
  def add_product_to_cart(product)
  ci = cart_items.build
  ci.product = product
  ci.quantity = 1
  ci.save
  end
  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end
  def clean!
   cart_items.destroy_all
 end
end

jdstore/app/models/cart_item.rb
class CartItem <ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

jdstore/app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

jdstore/app/models/order.rb
class Order < ApplicationRecord
  before_create :generate_token
  def generate_token
  self.token = SecureRandom.uuid
  end
  belongs_to :user
  has_many :product_lists
  validates :billing_name, presence: true
  validates :billing_address, presence: true
  # validates :shipping_name, presence: true
  # validates :shipping_address, presence: true
  def set_payment_with!(method)
  self.update_columns(payment_method: method )
  end

  def pay!
  self.update_columns(is_paid: true )
  end
  include AASM

  # aasm do
  #   state :order_placed, initial: true
  #   state :paid
  #   state :shipping
  #   state :shipped
  #   state :order_cancelled
  #   state :good_returned
  #
  #
  #      event :make_payment, after_commit: :pay! do
  #     transitions from: :order_placed, to: :paid
  #   end
  #
  #   event :ship do
  #     transitions from: :paid,         to: :shipping
  #   end
  #
  #   event :deliver do
  #     transitions from: :shipping,     to: :shipped
  #   end
  #
  #   event :return_good do
  #     transitions from: :shipped,      to: :good_returned
  #   end
  #
  #   event :cancel_order do
  #     transitions from: [:order_placed, :paid], to: :order_cancelled
  #   end
  # end

  aasm do
    state :已下单, initial: true
    state :已付款
    state :出货中
    state :已出货
    state :订单已取消
    state :退货


       event :make_payment, after_commit: :pay! do
      transitions from: :已下单, to: :已付款
    end

    event :ship do
      transitions from: :已付款,         to: :出货中
    end

    event :deliver do
      transitions from: :出货中,     to: :已出货
    end

    event :return_good do
      transitions from: :已出货,      to: :退货
    end

    event :cancel_order do
      transitions from: [:已下单, :已付款], to: :订单已取消
    end
  end
end

jdstore/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

jdstore/app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

jdstore/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
      def admin?
            is_admin
      end
      has_many :orders        
end

jdstore/app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @cart_item.product
    @cart_item.destroy

    flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
    redirect_to :back
  end
  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @cart_item.update(cart_item_params)

    redirect_to carts_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

jdstore/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
   current_cart.clean!
   flash[:warning] = "已清空购物车"
   redirect_to carts_path
 end
 def checkout
    @order = Order.new
  end
end

jdstore/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def pay_with_alipay
      @order = Order.find_by_token(params[:id])
      @order.set_payment_with!("alipay")
      @order.make_payment!


      redirect_to order_path(@order.token), notice: "使用支付宝成功完成付款"
    end

    def pay_with_wechat
      @order = Order.find_by_token(params[:id])
      @order.set_payment_with!("wechat")
      @order.make_payment!
      redirect_to order_path(@order.token), notice: "使用微信成功完成付款"
    end
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save!
      current_cart.cart_items.each do |cart_item|
          product_list = ProductList.new
          product_list.order = @order
          product_list.product_name = cart_item.product.title
          product_list.product_price = cart_item.product.price
          product_list.quantity = cart_item.quantity
          product_list.save
        end
        current_cart.clean!
        OrderMailer.notify_order_placed(@order).deliver!
      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end
  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
end
  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address, :telephone)
  end
end

jdstore/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    if params[:category].present?
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id)
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def search
    if @query_string.present?
      @products = search_params
    else
      @products = Product.all
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
  end

  private

  def search_params
    Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true).paginate(:page => params[:page], :per_page => 5 )
  end
end

jdstore/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all    
  end
end

jdstore/app/helpers/application_helper.rb
module ApplicationHelper
end

jdstore/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

jdstore/app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

jdstore/app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

jdstore/app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_paid_state(order)
   if order.is_paid?
     "已付款"
   else
     "未付款"
   end
 end
end

jdstore/app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

jdstore/app/helpers/welcome_helper.rb
module WelcomeHelper
end

jdstore/app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

jdstore/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">版权 ©2018 数码商城
        <br>由陈柄坤设计

    </p>
</footer>

jdstore/app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse"role="navigation" >
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">首页</a>
    </div>

          <div>
            <form class="navbar-form navbar-left" role="search">
              <%= form_tag search_products_path , :method => :get, :class => "form-search" do %>
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入搜索商品">
                </div>
                  <button type="submit" class="btn btn-default">搜索</button>
              <% end %>
            </form>
          </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <li>
          <%= link_to("我的订单", account_orders_path) %>
          </li>
        <% end %>

          <li>
            <%= link_to carts_path do  %>
              购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
            <% end %>
          </li>

        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %> </li>
          <li><%= link_to(content_tag(:i, '登录', class: 'fa fa-sign-in'), new_user_session_path) %></li>
        <% else %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li>
                  <%= link_to("管理员入口", admin_products_path ) %>
                </li>
            <% end %>
              <li>
                <%= link_to(content_tag(:i, '退出登录', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %>
              </li>
            </ul>
          </li>
          <% end %>
      </ul>


      <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

jdstore/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>管理后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("商品列表", admin_products_path) %> </li>
          <li> <%= link_to("订单", admin_orders_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

jdstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>数码购物商城 </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>