jdstore/config/routes.rb
Rails.application.routes.draw do
  # root 'products#index'
  devise_for :users

  namespace :admin do
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :products
  end

  resources :products do
    collection do
      get :search
    end

    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  get '/welcome' => 'welcome#index'
  root 'welcome#index'
end

jdstore/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  mount_uploader :image, ImageUploader
end

jdstore/app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :admin_required
  def index
   @products = Product.all
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def edit
     @product = Product.find(params[:id])
  end

  def update
     @product = Product.find(params[:id])

     if @product.update(product_params)
       redirect_to admin_products_path
     else
       render :edit
     end
  end
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
  end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id)
  end
end

jdstore/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]

  def index
    if params[:category].present?
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id)
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
    else
      flash[:warning] = "你的购物车内已有此物品"
    end
    redirect_to :back
  end

  def search
    if @query_string.present?
      @products = search_params
    else
      @products = Product.all
    end
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
  end

  private

  def search_params
    Product.ransack({:title_or_description_cont => @query_string}).result(distinct: true).paginate(:page => params[:page], :per_page => 5 )
  end
end

jdstore/app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

jdstore/app/helpers/products_helper.rb
module ProductsHelper
  def render_highlight_content(product,query_string)
    excerpt_cont = excerpt(product.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

jdstore/app/views/admin/products/edit.html.erb
<h2> 编辑产品 </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title ,label:'品牌'%>
  </div>

  <div class="group">
    <%= f.input :description,label:'详情' %>
  </div>

  <div class="group">
    <%= f.input :quantity,label:'库存' %>
  </div>

  <div class="group">
    <%= f.input :price,label:'价格' %>
  </div>
  <% if @product.image.present? %>
     <span>目前商品图</span> <br>
     <%= image_tag(@product.image.thumb.url) %>
   <% end %>

   <div class="group">
     <%= f.association :category %>
   </div>

   <div class="group">
     <%= f.input :image, as: :file,label:'图片' %>
   </div>
  <%= f.submit "提交", data: { disable_with: "Submitting..." } %>

<% end %>

jdstore/app/views/admin/products/index.html.erb
<h2> 商品管理表 </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">图片</th>
      <th>商品名</th>
      <th>价格</th>
      <th width="100"> 选项</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("编辑", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

jdstore/app/views/admin/products/new.html.erb
<h2> 新增产品</h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title,label:'新增产品'%>
  </div>

  <div class="group">
    <%= f.input :description,label:'描述' %>
  </div>

  <div class="group">
    <%= f.input :quantity,label:'数量' %>
  </div>

  <div class="group">
    <%= f.input :price ,label:'价格'%>
  </div>

  <div class="group">
   <%= f.input :image,label:'图片' ,as: :file %>
  </div>

  <div class="group">
    <%= f.association :category %>
  </div>

  <%= f.submit "提交", data: { disable_with: "Submitting..." } %>

<% end %>